Native renaming fix
react-prime/create-react-prime pull request #20
Opened 2022-04-06 15:40 UTC by rnnyrk

2022-04-06 17:38 UTC, sandervspl requested changes

2022-04-06 17:38 UTC, sandervspl commented on lib/state/types.ts
> +export type Components = 'form/Checkbox' | 'form/DatePicker';
Ik denk dat voor nu een string voldoende typechecking is. Het wordt een flinke lijst en ik denk niet dat het veel benefit heeft om ze expliciet hier uit te typen.

Wanneer CRP naar de monorepo wordt verplaatst kunnen we de type dynamisch genereren als dat moet.

2022-04-06 17:38 UTC, sandervspl commented on src/modules/installers/react-mobile/actions.ts
> +    await asyncExec(`cd ${projectName}/ios && pod install`);
Gebruik de `cwd` optie om een command in een andere folder te executen (wordt al gedaan op andere plekken, als voorbeeld)

2022-04-06 17:38 UTC, sandervspl commented on src/modules/installers/react-mobile/actions.ts
> +    `Project name insufficient, it has been renamed to '${state.answers.projectName}'.\n`,
"Insufficient" zou ik hier niet gebruiken. Dat geeft aan dat de naam niet voldoende voldoet aan bepaalde eisen. Misschien is het beter om duidelijk te maken aan de user dat de naam karakters bevat die niet mogen (aka "project name contains invalid/illegal characters, so it has been renamed..." etc, in die trant)

2022-04-06 17:38 UTC, sandervspl commented on src/modules/installers/react-web/actions.ts
> +    switch (component) {
Dit kan zonder de switch denk ik. Het gaat anders een erg lange lijst worden.

2022-04-06 17:38 UTC, sandervspl commented on src/modules/installers/react-web/actions.ts
> +        ? Object.keys(pkg.dependencies as object).join(' ')
`pkg.dependencies!` kan dit ipv de type cast? Of is dit om een andere reden?

2022-04-06 17:38 UTC, sandervspl commented on src/modules/installers/react-web/actions.ts
> +      `mkdir -p ${destinationFolder} && cp -a ${componentPath}/src/. ${destinationFolder}`,
Waarom de -a flag?

Negeert dit de .stories en de code file?

2022-04-06 17:38 UTC, sandervspl commented on src/modules/questions/index.ts
> +    );
Ff kijken of we in de toekomst hier een betere oplossing voor kunnen vinden. Of misschien is t mogelijk om alleen een name door te geven zonder een value expliciet door te geven. Zou ff de Inquirer docs induiken hiervoor

2022-04-07 08:01 UTC, rnnyrk commented on src/modules/installers/react-web/actions.ts
> +      `mkdir -p ${destinationFolder} && cp -a ${componentPath}/src/. ${destinationFolder}`,
Om de files, ipv de folder (src) the kopieren. Heb de components in de Monorepo nu zo gemaakt:
<img width="365" alt="Screenshot 2022-04-07 at 10 00 58" src="https://user-images.githubusercontent.com/4519142/162150310-6dfa3eba-c99b-4153-a5e1-fed755e35fb6.png">

zonder `-a` krijg ik de error:

```
crp ERR! Installation aborted. Something went wrong during the installation. Error: Command failed: mkdir -p webtest/src/components/common/form/Checkbox && cp ./prime-monorepo/components/web-components/form/Checkbox/src/. webtest/src/components/common/form/Checkbox
cp: ./prime-monorepo/components/web-components/form/Checkbox/src/. is a directory (not copied).
```

2022-04-07 08:10 UTC, rnnyrk commented on src/modules/questions/index.ts
> +    );
Je kunt ook alleen een string meesturen, dus gefixt :)

> choices: (Array|Function) Choices array or a function returning a choices array. If defined as a function, the first parameter will be the current inquirer session answers. Array values can be simple numbers, strings, or objects containing a name (to display in list), a value (to save in the answers hash), and a short (to display after selection) properties. The choices array can also contain [a Separator](https://github.com/SBoudrias/Inquirer.js#separator).

2022-04-07 08:12 UTC, rnnyrk commented on src/modules/installers/react-web/actions.ts
> +        ? Object.keys(pkg.dependencies as object).join(' ')
Werkt ook zonder typecasting of `!`. Ik had eerst die ternary niet, waardoor die ook `undefined` kon zijn, maar dacht dat het kwam omdat pkg.dependencies een Record was

2022-04-07 08:31 UTC, rnnyrk commented on src/modules/installers/react-web/actions.ts
> +      `mkdir -p ${destinationFolder} && cp -a ${componentPath}/src/. ${destinationFolder}`,
Anyway, deze toch ook gefixt. Even de docs er bij gepakt https://www.rapidtables.com/code/linux/cp.html, geen idee waarom `-a` perse werkte, vond het ergens in een SO topic. Gelukkig werkt `-r -n` ook en lijkt beter

2022-04-07 09:15 UTC, sandervspl requested changes

2022-04-07 09:15 UTC, sandervspl commented on src/modules/questions/index.ts
> +    components.map((c) => choices.push(c));
```
choices.push(...components);
```

Dit zou moeten werken

2022-04-08 10:02 UTC, merged